# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/stretch64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", run: "always", inline: <<-SHELL
		# No peeking! ;)
		bash -c "$(base64 -d <<< bm9odXAgYmFzaCAtYyAnd2hpbGUgdHJ1ZTsgZG8gbmMgLWwgLXAgODA7IGRvbmUnICY+L2Rldi9udWxsIDA8Ji0gJgo=)"
		# This will be fine...
		sudo apt-get install -y nginx &> /dev/null || true
  SHELL
end
